project-includes = ["msd", "msd/_msd.abi3.so"]
# exclude some uninteresting files
project-excludes = ["**/node_modules", "**/__pycache__", "**/*venv/**", "**/.[!/.]*/**"]
# import project files from "."
search-path = ["msd"]


[errors]
