project-includes = ["pymsd", "pymsd/_msd.abi3.so"]
# exclude some uninteresting files
project-excludes = ["**/node_modules", "**/__pycache__", "**/*venv/**", "**/.[!/.]*/**"]
# import project files from "."
search-path = ["."]


[errors]
